"""Ttitle extra space

Revision ID: 276faad4b3b4
Revises: 0c414d1e3338
Create Date: 2023-01-14 20:08:38.241884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '276faad4b3b4'
down_revision = '0c414d1e3338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=28),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=28),
               existing_nullable=False)

    # ### end Alembic commands ###
