"""a

Revision ID: 6e4002b9872b
Revises: 8c4a4d5109e6
Create Date: 2023-01-14 03:31:58.774547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e4002b9872b'
down_revision = '8c4a4d5109e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_ibfk_1', type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('posts_ibfk_1', 'users', ['poster_id'], ['id'])

    # ### end Alembic commands ###
