"""add pictures.

Revision ID: 90297429a39a
Revises: 276faad4b3b4
Create Date: 2023-02-09 21:18:09.902838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90297429a39a'
down_revision = '276faad4b3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_pic', sa.String(length=380), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('post_pic')

    # ### end Alembic commands ###
